### ISSUE TITLE
getting error running npm run dev

### ISSUE THREAD

**Issue by chrisvwlc** [davidyeiser/detailer#7]
Hi. Thank you so much for creating this tutorial! I am stuck; however, and hope you can help. When I run npm run dev I get the following error message: ERROR in Entry module not found: Error: Can't resolve './blocks/book-details/editor.css' in '/Applications/MAMP/htdocs/newsg/wp-content/plugins/detailer'.
Should I be creating editor.css before running it?

**Comment by davidyeiser** [comment]
Hey @chrisvwlc, thanks for reporting this. Yes the `editor.css` and `style.css` should be created before running `yarn dev` (or `npm run dev`). I've updated the tutorial to reflect this. Let me know if you have any more issues. Thanks!
